Prepare for cmcc 12
CoreMedia/content-hub-adapter-youtube pull request #13
Opened 2024-01-08 12:54 UTC by uwilken

2024-01-09 12:42 UTC, pitgrap approved these changes

2024-01-09 12:42 UTC, pitgrap commented on .github/workflows/build.yml
> +        uses: actions/checkout@v4.1.1
same as in https://github.com/CoreMedia/content-hub-adapter-rss/pull/12#pullrequestreview-1811070817

2024-01-09 12:42 UTC, pitgrap commented on .github/workflows/build.yml
> +        uses: actions/setup-java@v4.0.0
and here

2024-01-10 09:02 UTC, pitgrap requested changes
still one version change in github action missing.

Also missing:
- Changelog for 2.1.0
- change the version to 2310 in README icon

2024-01-10 09:06 UTC, uwilken commented
> * change the version to 2310 in README icon

Depends on the meaning of the badge. Does it mean the current or the minimum cms version?

2024-01-10 09:38 UTC, pitgrap commented
🤷‍♂️

2024-01-10 13:21 UTC, mkleine approved these changes
lgtm

2024-01-11 16:21 UTC, merged